site_name: 'Forecasting'
site_description: 'Main documentation for the forecasting domain'
repo_url: https://github.com/jacobduijzer/BackstageDemoProjects/tree/main/domain/forecasting
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  
nav:
  - Overview: 'overview.md'
  - Architecture:
    - 'Context': 'architecture/context.md'
    - 'Containers': 'architecture/containers.md'
    - 'Components': 'architecture/components.md'
