site_name: 'Pizza Shop'
site_description: 'Main documentation for the overall Pizza Shop domain'
repo_url: https://github.com/jacobduijzer/BackstageDemoProjects/tree/main/pizzashop/domains/orders
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  
nav:
  - Overview: 'overview.md'
