apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: weather-forecasting
  description: Everything related to weather forecasting.
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: group:default/rockstars 
  domain: weather
