apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: weather-history
  description: Everything related to the history of weather forcasting.
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: group:default/backstage_team
  dependsOn: ['domain:weather']
