apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: group:default/rockstars
  system: artist-engagement-portal
  definition: 
    $text: https://github.com/jacobduijzer/BackstageDemoProjects/tree/main/weatherapi/WeatherApi.Api/swagger.json