apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
  {
    "openapi": "3.0.1",
    "info": {
      "title": "WeatherApi.Api",
      "version": "1.0"
    },
    "paths": {
      "/WeatherForecast": {
        "get": {
          "tags": [
            "WeatherForecast"
          ],
          "operationId": "GetWeatherForecast",
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/WeatherForecast"
                    }
                  }
                },
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/WeatherForecast"
                    }
                  }
                },
                "text/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/WeatherForecast"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "WeatherForecast": {
          "type": "object",
          "properties": {
            "date": {
              "type": "string",
              "format": "date-time"
            },
            "temperatureC": {
              "type": "integer",
              "format": "int32"
            },
            "temperatureF": {
              "type": "integer",
              "format": "int32",
              "readOnly": true
            },
            "summary": {
              "type": "string",
              "nullable": true
            }
          },
          "additionalProperties": false
        }
      }
    }
  }
