apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather-service
  description: Weather API
  tags:
    - dotnet
    - csharp
    - webapi
spec:
  type: service
  lifecycle: production
  owner: group:default/backstage_team
  system: forecasting-system
  providesApis: 
    - weather-api
