name: Publish Domain TechDocs

on:
  push:
    branches:
      - main
    paths:
      - "domain/weather/**"
      - ".github/workflows/domain-weather-docs.yml"
  workflow_dispatch:
    
jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    env:
      TECHDOCS_CONTAINER_NAME: 'techdocs'
      TECHDOCS_STORAGE_ACCOUNT: ${{ secrets.TECHDOCS_STORAGE_ACCOUNT  }}
      TECHDOCS_STORAGE_ACCOUNT_KEY: ${{ secrets.TECHDOCS_STORAGE_ACCOUNT_KEY  }}
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Domain'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
      
      - name: download, validate, install plantuml and its dependencies
        run: |
          curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download
          echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c -
          mv plantuml.jar /opt/plantuml.jar
          mkdir -p "$HOME/.local/bin"
          echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> "$HOME/.local/bin/plantuml"
          chmod +x "$HOME/.local/bin/plantuml"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          sudo apt-get install -y graphviz
      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Publish weather domain docs
        working-directory: ./domain/weather
        run: |
          techdocs-cli generate --no-docker --verbose
          techdocs-cli publish --publisher-type azureBlobStorage --azureAccountName $TECHDOCS_STORAGE_ACCOUNT --azureAccountKey $TECHDOCS_STORAGE_ACCOUNT_KEY --storage-name $TECHDOCS_CONTAINER_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/weather
          
      - name: Publish weather history docs
        working-directory: ./domain/weather-history
        run: |
          techdocs-cli generate --no-docker --verbose
          techdocs-cli publish --publisher-type azureBlobStorage --azureAccountName $TECHDOCS_STORAGE_ACCOUNT --azureAccountKey $TECHDOCS_STORAGE_ACCOUNT_KEY --storage-name $TECHDOCS_CONTAINER_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/weather-history
          
      - name: Publish weather forecasting docs
        working-directory: ./domain/weather-forecasting
        run: |
          techdocs-cli generate --no-docker --verbose
          techdocs-cli publish --publisher-type azureBlobStorage --azureAccountName $TECHDOCS_STORAGE_ACCOUNT --azureAccountKey $TECHDOCS_STORAGE_ACCOUNT_KEY --storage-name $TECHDOCS_CONTAINER_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/weather-forecasting   
